sudo: true
os: trusty
cache: false
env:
- URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
before_install:
- openssl aes-256-cbc -K 1209cd966a56596a2727fdcd5dc1d507e69c9695bee1d7943234505551b42304 -iv cfea0db67c3852b6ec7c39e0edaeec69  -in assets/server.key.enc -out assets/server.key -d
- export SFDX_AUTOUPDATE_DISABLE=false
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- export SFDX_DISABLE_APP_HUB=true
- export SFDX_LOG_LEVEL=DEBUG
- mkdir sfdx
- wget -qO- $URL | tar xJ -C sfdx --strip-components 1
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx --version
- sfdx plugins --core
- sfdx force:auth:jwt:grant --clientid 3MVG9JZ_r.QzrS7hZ1OKVYFzPMBnkAgVxxg_flP9JSiihzW9EIlpleU3ZZqNqUDwsy4ZIfwIO9Apl2fIxMTsE --jwtkeyfile assets/server.key
  --username barathanv@31demo.com --setdefaultdevhubusername -a DevHub 
script:
- sfdx force:org:create -v HubOrg -s -f config/project-scratch-def.json -a citestorg1  --json  --loglevel error
- sfdx force:org:display -u citestorg1
- sfdx force:source:push -u citestorg1
- sfdx force:apex:test:run -u citestorg1 --wait 10
- sfdx force:org:delete -u citestorg1 -p
